Satisfy case with multiple vision targets in frame
Tino-FRC-2473/FRC2019-Vision pull request #2
Opened 2019-01-10 01:57 UTC by mvoodarla

This code checks to find the two closest, largest rectangles in frame to counteract problems with the robot being confused when it sees multiple vision targets. Also, I removed some unneeded comments and shortened some of the swapping code. I also removed the side case since we won't encounter that.

2019-01-12 07:31 UTC, Pkfire26 commented
For distance, can we isolate the corners of the rectangle, and then compare the pixel length between two of the points with their actual dimensions to find distance to the target?

2019-01-13 04:58 UTC, AG6GR commented on cv.py
> +        self.DIST_CONSTANT = 3300 # dist_constant = focal_length * actual_height_of_reflective_tape
One last thing I forgot to mention: All of these distances are physical length units (mm/in etc). The size of the rectangle on your image is in pixels. There is one last conversion from pixels to physical length, which can be done with the physical sensor size of your camera. That might be hard to find online, but you can directly measure it, or design some experiments to derive it empirically.

2019-01-15 08:07 UTC, AG6GR commented
Just a reminder, make sure to write descriptive commit messages! See https://chris.beams.io/posts/git-commit/ for guidance.

I'd recommend closing this review and starting a new one based on the commit before the reverts.

2019-01-19 04:15 UTC, AG6GR commented on cv.py
> +        self.FOCAL_LENGTH_PIXELS = (self.SCREEN_WIDTH / 2.0) / math.tan(self.FIELD_OF_VIEW_RAD / 2.0) #angle constant is the same as focal length of camera (pixels)
Can you update the comment? Ideally explain this formula.

2019-01-19 04:16 UTC, AG6GR commented on cv.py
> +            return (self.FOCAL_LENGTH_PIXELS * 5.5) / length
What's 5.5? How did you find this number?

2019-01-19 04:17 UTC, AG6GR commented on cv.py
> +        def sort_by_area(c):
What is this?

2019-01-19 04:19 UTC, AG6GR commented on cv.py
> +            cv2.drawContours(frame,[rotated_rect1.box],0,(0,0,255),2)
Spaces after commas please. Just like regular English.

2019-01-19 04:21 UTC, AG6GR commented on cv.py
> +            #i dont know how the points work
Can we change this comment to explain how the points work? Also next time if you don't understand something, feel free to ask on Slack. We're all learning together, it's ok to have questions.

2019-01-19 04:23 UTC, AG6GR commented on cv.py
> +        self.box = box
It might be helpful to comment what type you expect some of these variables to be. Especially if they are an object rather than a simple type.

2019-01-19 04:25 UTC, AG6GR commented on run.py
> +    print str(angle), str(distance)
Is there a reason we aren't using Python3?

For bonus points, take a look at https://pyformat.info/ . format() is a really awesome feature of Python that makes printing stuff like this much cleaner.

2019-01-19 04:25 UTC, AG6GR commented on test.py
> +    time.sleep(0.1)
Just curious what happens if you don't do time.sleep()?

2019-01-19 04:27 UTC, AG6GR requested changes
Some minor cleanup changes. I didn't go over the code logic in detail, we can talk about that tomorrow.

For code style, I'm going off the [PEP8](https://www.python.org/dev/peps/pep-0008/) Python standard.

2019-01-19 04:32 UTC, mvoodarla commented on run.py
> +    print str(angle), str(distance)
We honestly should use Python3.

2019-01-19 04:54 UTC, AG6GR commented on run.py
> +    print str(angle), str(distance)
Let's discuss this at a future meeting. It isn't exactly a trivial change since we would have to set up OpenCV again for everyone in Python 3.

2019-01-19 17:25 UTC, michelllepan commented on cv.py
> +        self.box = box
resolved by b0cf155

2019-01-19 17:26 UTC, michelllepan commented on cv.py
> +            #i dont know how the points work
resolved by b0cf155

2019-01-19 17:26 UTC, michelllepan commented on cv.py
> +            cv2.drawContours(frame,[rotated_rect1.box],0,(0,0,255),2)
resolved by b0cf155

2019-01-19 17:26 UTC, michelllepan commented on cv.py
> +        def sort_by_area(c):
resolved by b0cf155

2019-01-19 17:27 UTC, michelllepan commented on cv.py
> +        self.FOCAL_LENGTH_PIXELS = (self.SCREEN_WIDTH / 2.0) / math.tan(self.FIELD_OF_VIEW_RAD / 2.0) #angle constant is the same as focal length of camera (pixels)
resolved by b0cf155

2019-01-21 07:57 UTC, AG6GR approved these changes

2019-01-21 18:08 UTC, merged